package net.minestom.server.potion;

import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * //==============================
 * //  AUTOGENERATED BY EnumGenerator
 * //==============================
 */
@SuppressWarnings({"deprecation"})
public enum PotionEffect {
    SPEED("minecraft:Speed"),

    SLOWNESS("minecraft:Slowness"),

    HASTE("minecraft:Haste"),

    MINING_FATIGUE("minecraft:MiningFatigue"),

    STRENGTH("minecraft:Strength"),

    INSTANT_HEALTH("minecraft:InstantHealth"),

    INSTANT_DAMAGE("minecraft:InstantDamage"),

    JUMP_BOOST("minecraft:JumpBoost"),

    NAUSEA("minecraft:Nausea"),

    REGENERATION("minecraft:Regeneration"),

    RESISTANCE("minecraft:Resistance"),

    FIRE_RESISTANCE("minecraft:FireResistance"),

    WATER_BREATHING("minecraft:WaterBreathing"),

    INVISIBILITY("minecraft:Invisibility"),

    BLINDNESS("minecraft:Blindness"),

    NIGHT_VISION("minecraft:NightVision"),

    HUNGER("minecraft:Hunger"),

    WEAKNESS("minecraft:Weakness"),

    POISON("minecraft:Poison"),

    WITHER("minecraft:Wither"),

    HEALTH_BOOST("minecraft:HealthBoost"),

    ABSORPTION("minecraft:Absorption"),

    SATURATION("minecraft:Saturation");

    private String namespaceID;

    PotionEffect(String namespaceID) {
        this.namespaceID = namespaceID;
        Registries.potionEffects.put(NamespaceID.from(namespaceID), this);
    }

    public int getId() {
        return ordinal() + 1;
    }

    public String getNamespaceID() {
        return namespaceID;
    }

    public static PotionEffect fromId(int id) {
        if (id >= 0 && id < values().length + 1) {
            return values()[id - 1];
        }
        return null;
    }
}
