package net.minestom.server.item;

import net.minestom.server.instance.block.Block;
import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * //==============================
 * //  AUTOGENERATED BY EnumGenerator
 * //==============================
 */
@SuppressWarnings({"deprecation"})
public enum Material {
    AIR("minecraft:air", 64, Block.AIR),

    STONE("minecraft:stone", 64, Block.STONE),

    GRASS("minecraft:grass", 64, Block.GRASS),

    DIRT("minecraft:dirt", 64, Block.DIRT),

    COBBLESTONE("minecraft:cobblestone", 64, Block.COBBLESTONE),

    PLANKS("minecraft:planks", 64, Block.PLANKS),

    SAPLING("minecraft:sapling", 64, Block.SAPLING),

    BEDROCK("minecraft:bedrock", 64, Block.BEDROCK),

    SAND("minecraft:sand", 64, Block.SAND),

    GRAVEL("minecraft:gravel", 64, Block.GRAVEL),

    GOLD_ORE("minecraft:gold_ore", 64, Block.GOLD_ORE),

    IRON_ORE("minecraft:iron_ore", 64, Block.IRON_ORE),

    COAL_ORE("minecraft:coal_ore", 64, Block.COAL_ORE),

    LOG("minecraft:log", 64, Block.LOG),

    LEAVES("minecraft:leaves", 64, Block.LEAVES),

    SPONGE("minecraft:sponge", 64, Block.SPONGE),

    GLASS("minecraft:glass", 64, Block.GLASS),

    LAPIS_ORE("minecraft:lapis_ore", 64, Block.LAPIS_ORE),

    LAPIS_BLOCK("minecraft:lapis_block", 64, Block.LAPIS_BLOCK),

    DISPENSER("minecraft:dispenser", 64, Block.DISPENSER),

    SANDSTONE("minecraft:sandstone", 64, Block.SANDSTONE),

    NOTEBLOCK("minecraft:noteblock", 64, Block.NOTEBLOCK),

    GOLDEN_RAIL("minecraft:golden_rail", 64, Block.GOLDEN_RAIL),

    DETECTOR_RAIL("minecraft:detector_rail", 64, Block.DETECTOR_RAIL),

    STICKY_PISTON("minecraft:sticky_piston", 64, Block.STICKY_PISTON),

    WEB("minecraft:web", 64, Block.WEB),

    TALLGRASS("minecraft:tallgrass", 64, Block.TALLGRASS),

    DEADBUSH("minecraft:deadbush", 64, Block.DEADBUSH),

    PISTON("minecraft:piston", 64, Block.PISTON),

    WOOL("minecraft:wool", 64, Block.WOOL),

    YELLOW_FLOWER("minecraft:yellow_flower", 64, Block.YELLOW_FLOWER),

    RED_FLOWER("minecraft:red_flower", 64, Block.RED_FLOWER),

    BROWN_MUSHROOM("minecraft:brown_mushroom", 64, Block.BROWN_MUSHROOM),

    RED_MUSHROOM("minecraft:red_mushroom", 64, Block.RED_MUSHROOM),

    GOLD_BLOCK("minecraft:gold_block", 64, Block.GOLD_BLOCK),

    IRON_BLOCK("minecraft:iron_block", 64, Block.IRON_BLOCK),

    STONE_SLAB("minecraft:stone_slab", 64, Block.STONE_SLAB),

    BRICK_BLOCK("minecraft:brick_block", 64, Block.BRICK_BLOCK),

    TNT("minecraft:tnt", 64, Block.TNT),

    BOOKSHELF("minecraft:bookshelf", 64, Block.BOOKSHELF),

    MOSSY_COBBLESTONE("minecraft:mossy_cobblestone", 64, Block.MOSSY_COBBLESTONE),

    OBSIDIAN("minecraft:obsidian", 64, Block.OBSIDIAN),

    TORCH("minecraft:torch", 64, Block.TORCH),

    MOB_SPAWNER("minecraft:mob_spawner", 64, Block.MOB_SPAWNER),

    OAK_STAIRS("minecraft:oak_stairs", 64, Block.OAK_STAIRS),

    CHEST("minecraft:chest", 64, Block.CHEST),

    DIAMOND_ORE("minecraft:diamond_ore", 64, Block.DIAMOND_ORE),

    DIAMOND_BLOCK("minecraft:diamond_block", 64, Block.DIAMOND_BLOCK),

    CRAFTING_TABLE("minecraft:crafting_table", 64, Block.CRAFTING_TABLE),

    FARMLAND("minecraft:farmland", 64, Block.FARMLAND),

    FURNACE("minecraft:furnace", 64, Block.FURNACE),

    LIT_FURNACE("minecraft:lit_furnace", 64, Block.LIT_FURNACE),

    LADDER("minecraft:ladder", 64, Block.LADDER),

    RAIL("minecraft:rail", 64, Block.RAIL),

    STONE_STAIRS("minecraft:stone_stairs", 64, Block.STONE_STAIRS),

    LEVER("minecraft:lever", 64, Block.LEVER),

    STONE_PRESSURE_PLATE("minecraft:stone_pressure_plate", 64, Block.STONE_PRESSURE_PLATE),

    WOODEN_PRESSURE_PLATE("minecraft:wooden_pressure_plate", 64, Block.WOODEN_PRESSURE_PLATE),

    REDSTONE_ORE("minecraft:redstone_ore", 64, Block.REDSTONE_ORE),

    REDSTONE_TORCH("minecraft:redstone_torch", 64, Block.REDSTONE_TORCH),

    STONE_BUTTON("minecraft:stone_button", 64, Block.STONE_BUTTON),

    SNOW_LAYER("minecraft:snow_layer", 64, Block.SNOW_LAYER),

    ICE("minecraft:ice", 64, Block.ICE),

    SNOW("minecraft:snow", 64, Block.SNOW),

    CACTUS("minecraft:cactus", 64, Block.CACTUS),

    CLAY("minecraft:clay", 64, Block.CLAY),

    JUKEBOX("minecraft:jukebox", 64, Block.JUKEBOX),

    FENCE("minecraft:fence", 64, Block.FENCE),

    PUMPKIN("minecraft:pumpkin", 64, Block.PUMPKIN),

    NETHERRACK("minecraft:netherrack", 64, Block.NETHERRACK),

    SOUL_SAND("minecraft:soul_sand", 64, Block.SOUL_SAND),

    GLOWSTONE("minecraft:glowstone", 64, Block.GLOWSTONE),

    LIT_PUMPKIN("minecraft:lit_pumpkin", 64, Block.LIT_PUMPKIN),

    STAINED_GLASS("minecraft:stained_glass", 64, Block.STAINED_GLASS),

    TRAPDOOR("minecraft:trapdoor", 64, Block.TRAPDOOR),

    MONSTER_EGG("minecraft:monster_egg", 64, Block.MONSTER_EGG),

    STONEBRICK("minecraft:stonebrick", 64, Block.STONEBRICK),

    BROWN_MUSHROOM_BLOCK("minecraft:brown_mushroom_block", 64, Block.BROWN_MUSHROOM_BLOCK),

    RED_MUSHROOM_BLOCK("minecraft:red_mushroom_block", 64, Block.RED_MUSHROOM_BLOCK),

    IRON_BARS("minecraft:iron_bars", 64, Block.IRON_BARS),

    GLASS_PANE("minecraft:glass_pane", 64, Block.GLASS_PANE),

    MELON_BLOCK("minecraft:melon_block", 64, Block.MELON_BLOCK),

    VINE("minecraft:vine", 64, Block.VINE),

    FENCE_GATE("minecraft:fence_gate", 64, Block.FENCE_GATE),

    BRICK_STAIRS("minecraft:brick_stairs", 64, Block.BRICK_STAIRS),

    STONE_BRICK_STAIRS("minecraft:stone_brick_stairs", 64, Block.STONE_BRICK_STAIRS),

    MYCELIUM("minecraft:mycelium", 64, Block.MYCELIUM),

    WATERLILY("minecraft:waterlily", 64, Block.WATERLILY),

    NETHER_BRICK("minecraft:nether_brick", 64, Block.NETHER_BRICK),

    NETHER_BRICK_FENCE("minecraft:nether_brick_fence", 64, Block.NETHER_BRICK_FENCE),

    NETHER_BRICK_STAIRS("minecraft:nether_brick_stairs", 64, Block.NETHER_BRICK_STAIRS),

    ENCHANTING_TABLE("minecraft:enchanting_table", 64, Block.ENCHANTING_TABLE),

    END_PORTAL_FRAME("minecraft:end_portal_frame", 64, Block.END_PORTAL_FRAME),

    END_STONE("minecraft:end_stone", 64, Block.END_STONE),

    DRAGON_EGG("minecraft:dragon_egg", 64, Block.DRAGON_EGG),

    REDSTONE_LAMP("minecraft:redstone_lamp", 64, Block.REDSTONE_LAMP),

    WOODEN_SLAB("minecraft:wooden_slab", 64, Block.WOODEN_SLAB),

    SANDSTONE_STAIRS("minecraft:sandstone_stairs", 64, Block.SANDSTONE_STAIRS),

    EMERALD_ORE("minecraft:emerald_ore", 64, Block.EMERALD_ORE),

    ENDER_CHEST("minecraft:ender_chest", 64, Block.ENDER_CHEST),

    TRIPWIRE_HOOK("minecraft:tripwire_hook", 64, Block.TRIPWIRE_HOOK),

    EMERALD_BLOCK("minecraft:emerald_block", 64, Block.EMERALD_BLOCK),

    SPRUCE_STAIRS("minecraft:spruce_stairs", 64, Block.SPRUCE_STAIRS),

    BIRCH_STAIRS("minecraft:birch_stairs", 64, Block.BIRCH_STAIRS),

    JUNGLE_STAIRS("minecraft:jungle_stairs", 64, Block.JUNGLE_STAIRS),

    COMMAND_BLOCK("minecraft:command_block", 64, Block.COMMAND_BLOCK),

    BEACON("minecraft:beacon", 64, Block.BEACON),

    COBBLESTONE_WALL("minecraft:cobblestone_wall", 64, Block.COBBLESTONE_WALL),

    WOODEN_BUTTON("minecraft:wooden_button", 64, Block.WOODEN_BUTTON),

    ANVIL("minecraft:anvil", 64, Block.ANVIL),

    TRAPPED_CHEST("minecraft:trapped_chest", 64, Block.TRAPPED_CHEST),

    LIGHT_WEIGHTED_PRESSURE_PLATE("minecraft:light_weighted_pressure_plate", 64, Block.LIGHT_WEIGHTED_PRESSURE_PLATE),

    HEAVY_WEIGHTED_PRESSURE_PLATE("minecraft:heavy_weighted_pressure_plate", 64, Block.HEAVY_WEIGHTED_PRESSURE_PLATE),

    DAYLIGHT_DETECTOR("minecraft:daylight_detector", 64, Block.DAYLIGHT_DETECTOR),

    REDSTONE_BLOCK("minecraft:redstone_block", 64, Block.REDSTONE_BLOCK),

    QUARTZ_ORE("minecraft:quartz_ore", 64, Block.QUARTZ_ORE),

    HOPPER("minecraft:hopper", 64, Block.HOPPER),

    QUARTZ_BLOCK("minecraft:quartz_block", 64, Block.QUARTZ_BLOCK),

    QUARTZ_STAIRS("minecraft:quartz_stairs", 64, Block.QUARTZ_STAIRS),

    ACTIVATOR_RAIL("minecraft:activator_rail", 64, Block.ACTIVATOR_RAIL),

    DROPPER("minecraft:dropper", 64, Block.DROPPER),

    STAINED_HARDENED_CLAY("minecraft:stained_hardened_clay", 64, Block.STAINED_HARDENED_CLAY),

    STAINED_GLASS_PANE("minecraft:stained_glass_pane", 64, Block.STAINED_GLASS_PANE),

    LEAVES2("minecraft:leaves2", 64, Block.LEAVES2),

    LOG2("minecraft:log2", 64, Block.LOG2),

    ACACIA_STAIRS("minecraft:acacia_stairs", 64, Block.ACACIA_STAIRS),

    DARK_OAK_STAIRS("minecraft:dark_oak_stairs", 64, Block.DARK_OAK_STAIRS),

    SLIME("minecraft:slime", 64, Block.SLIME),

    BARRIER("minecraft:barrier", 64, Block.BARRIER),

    IRON_TRAPDOOR("minecraft:iron_trapdoor", 64, Block.IRON_TRAPDOOR),

    PRISMARINE("minecraft:prismarine", 64, Block.PRISMARINE),

    SEA_LANTERN("minecraft:sea_lantern", 64, Block.SEA_LANTERN),

    HAY_BLOCK("minecraft:hay_block", 64, Block.HAY_BLOCK),

    CARPET("minecraft:carpet", 64, Block.CARPET),

    HARDENED_CLAY("minecraft:hardened_clay", 64, Block.HARDENED_CLAY),

    COAL_BLOCK("minecraft:coal_block", 64, Block.COAL_BLOCK),

    PACKED_ICE("minecraft:packed_ice", 64, Block.PACKED_ICE),

    DOUBLE_PLANT("minecraft:double_plant", 64, Block.DOUBLE_PLANT),

    RED_SANDSTONE("minecraft:red_sandstone", 64, Block.RED_SANDSTONE),

    RED_SANDSTONE_STAIRS("minecraft:red_sandstone_stairs", 64, Block.RED_SANDSTONE_STAIRS),

    STONE_SLAB2("minecraft:stone_slab2", 64, Block.STONE_SLAB2),

    SPRUCE_FENCE_GATE("minecraft:spruce_fence_gate", 64, Block.SPRUCE_FENCE_GATE),

    BIRCH_FENCE_GATE("minecraft:birch_fence_gate", 64, Block.BIRCH_FENCE_GATE),

    JUNGLE_FENCE_GATE("minecraft:jungle_fence_gate", 64, Block.JUNGLE_FENCE_GATE),

    DARK_OAK_FENCE_GATE("minecraft:dark_oak_fence_gate", 64, Block.DARK_OAK_FENCE_GATE),

    ACACIA_FENCE_GATE("minecraft:acacia_fence_gate", 64, Block.ACACIA_FENCE_GATE),

    SPRUCE_FENCE("minecraft:spruce_fence", 64, Block.SPRUCE_FENCE),

    BIRCH_FENCE("minecraft:birch_fence", 64, Block.BIRCH_FENCE),

    JUNGLE_FENCE("minecraft:jungle_fence", 64, Block.JUNGLE_FENCE),

    DARK_OAK_FENCE("minecraft:dark_oak_fence", 64, Block.DARK_OAK_FENCE),

    ACACIA_FENCE("minecraft:acacia_fence", 64, Block.ACACIA_FENCE),

    IRON_SHOVEL("minecraft:iron_shovel", 64, null),

    IRON_PICKAXE("minecraft:iron_pickaxe", 64, null),

    IRON_AXE("minecraft:iron_axe", 64, null),

    FLINT_AND_STEEL("minecraft:flint_and_steel", 64, null),

    APPLE("minecraft:apple", 64, null),

    BOW("minecraft:bow", 64, null),

    ARROW("minecraft:arrow", 64, null),

    COAL("minecraft:coal", 64, null),

    DIAMOND("minecraft:diamond", 64, null),

    IRON_INGOT("minecraft:iron_ingot", 64, null),

    GOLD_INGOT("minecraft:gold_ingot", 64, null),

    IRON_SWORD("minecraft:iron_sword", 64, null),

    WOODEN_SWORD("minecraft:wooden_sword", 64, null),

    WOODEN_SHOVEL("minecraft:wooden_shovel", 64, null),

    WOODEN_PICKAXE("minecraft:wooden_pickaxe", 64, null),

    WOODEN_AXE("minecraft:wooden_axe", 64, null),

    STONE_SWORD("minecraft:stone_sword", 64, null),

    STONE_SHOVEL("minecraft:stone_shovel", 64, null),

    STONE_PICKAXE("minecraft:stone_pickaxe", 64, null),

    STONE_AXE("minecraft:stone_axe", 64, null),

    DIAMOND_SWORD("minecraft:diamond_sword", 64, null),

    DIAMOND_SHOVEL("minecraft:diamond_shovel", 64, null),

    DIAMOND_PICKAXE("minecraft:diamond_pickaxe", 64, null),

    DIAMOND_AXE("minecraft:diamond_axe", 64, null),

    STICK("minecraft:stick", 64, null),

    BOWL("minecraft:bowl", 64, null),

    MUSHROOM_STEW("minecraft:mushroom_stew", 64, null),

    GOLDEN_SWORD("minecraft:golden_sword", 64, null),

    GOLDEN_SHOVEL("minecraft:golden_shovel", 64, null),

    GOLDEN_PICKAXE("minecraft:golden_pickaxe", 64, null),

    GOLDEN_AXE("minecraft:golden_axe", 64, null),

    STRING("minecraft:string", 64, null),

    FEATHER("minecraft:feather", 64, null),

    GUNPOWDER("minecraft:gunpowder", 64, null),

    WOODEN_HOE("minecraft:wooden_hoe", 64, null),

    STONE_HOE("minecraft:stone_hoe", 64, null),

    IRON_HOE("minecraft:iron_hoe", 64, null),

    DIAMOND_HOE("minecraft:diamond_hoe", 64, null),

    GOLDEN_HOE("minecraft:golden_hoe", 64, null),

    WHEAT_SEEDS("minecraft:wheat_seeds", 64, null),

    WHEAT("minecraft:wheat", 64, Block.WHEAT),

    BREAD("minecraft:bread", 64, null),

    LEATHER_HELMET("minecraft:leather_helmet", 64, null),

    LEATHER_CHESTPLATE("minecraft:leather_chestplate", 64, null),

    LEATHER_LEGGINGS("minecraft:leather_leggings", 64, null),

    LEATHER_BOOTS("minecraft:leather_boots", 64, null),

    CHAINMAIL_HELMET("minecraft:chainmail_helmet", 64, null),

    CHAINMAIL_CHESTPLATE("minecraft:chainmail_chestplate", 64, null),

    CHAINMAIL_LEGGINGS("minecraft:chainmail_leggings", 64, null),

    CHAINMAIL_BOOTS("minecraft:chainmail_boots", 64, null),

    IRON_HELMET("minecraft:iron_helmet", 64, null),

    IRON_CHESTPLATE("minecraft:iron_chestplate", 64, null),

    IRON_LEGGINGS("minecraft:iron_leggings", 64, null),

    IRON_BOOTS("minecraft:iron_boots", 64, null),

    DIAMOND_HELMET("minecraft:diamond_helmet", 64, null),

    DIAMOND_CHESTPLATE("minecraft:diamond_chestplate", 64, null),

    DIAMOND_LEGGINGS("minecraft:diamond_leggings", 64, null),

    DIAMOND_BOOTS("minecraft:diamond_boots", 64, null),

    GOLDEN_HELMET("minecraft:golden_helmet", 64, null),

    GOLDEN_CHESTPLATE("minecraft:golden_chestplate", 64, null),

    GOLDEN_LEGGINGS("minecraft:golden_leggings", 64, null),

    GOLDEN_BOOTS("minecraft:golden_boots", 64, null),

    FLINT("minecraft:flint", 64, null),

    PORKCHOP("minecraft:porkchop", 64, null),

    COOKED_PORKCHOP("minecraft:cooked_porkchop", 64, null),

    PAINTING("minecraft:painting", 64, null),

    GOLDEN_APPLE("minecraft:golden_apple", 64, null),

    SIGN("minecraft:sign", 64, null),

    WOODEN_DOOR("minecraft:wooden_door", 64, Block.WOODEN_DOOR),

    BUCKET("minecraft:bucket", 16, null),

    WATER_BUCKET("minecraft:water_bucket", 64, null),

    LAVA_BUCKET("minecraft:lava_bucket", 64, null),

    MINECART("minecraft:minecart", 64, null),

    SADDLE("minecraft:saddle", 64, null),

    IRON_DOOR("minecraft:iron_door", 64, Block.IRON_DOOR),

    REDSTONE("minecraft:redstone", 64, Block.REDSTONE_WIRE),

    SNOWBALL("minecraft:snowball", 64, null),

    BOAT("minecraft:boat", 64, null),

    LEATHER("minecraft:leather", 64, null),

    MILK_BUCKET("minecraft:milk_bucket", 64, null),

    BRICK("minecraft:brick", 64, null),

    CLAY_BALL("minecraft:clay_ball", 64, null),

    REEDS("minecraft:reeds", 64, Block.REEDS),

    PAPER("minecraft:paper", 64, null),

    BOOK("minecraft:book", 64, null),

    SLIME_BALL("minecraft:slime_ball", 64, null),

    CHEST_MINECART("minecraft:chest_minecart", 64, null),

    FURNACE_MINECART("minecraft:furnace_minecart", 64, null),

    EGG("minecraft:egg", 64, null),

    COMPASS("minecraft:compass", 64, null),

    FISHING_ROD("minecraft:fishing_rod", 64, null),

    CLOCK("minecraft:clock", 64, null),

    GLOWSTONE_DUST("minecraft:glowstone_dust", 64, null),

    FISH("minecraft:fish", 64, null),

    COOKED_FISH("minecraft:cooked_fish", 64, null),

    DYE("minecraft:dye", 64, null),

    BONE("minecraft:bone", 64, null),

    SUGAR("minecraft:sugar", 64, null),

    CAKE("minecraft:cake", 1, Block.CAKE),

    BED("minecraft:bed", 1, Block.BED),

    REPEATER("minecraft:repeater", 64, Block.UNPOWERED_REPEATER),

    COOKIE("minecraft:cookie", 64, null),

    FILLED_MAP("minecraft:filled_map", 64, null),

    SHEARS("minecraft:shears", 64, null),

    MELON("minecraft:melon", 64, Block.MELON_BLOCK),

    PUMPKIN_SEEDS("minecraft:pumpkin_seeds", 64, null),

    MELON_SEEDS("minecraft:melon_seeds", 64, null),

    BEEF("minecraft:beef", 64, null),

    COOKED_BEEF("minecraft:cooked_beef", 64, null),

    CHICKEN("minecraft:chicken", 64, null),

    COOKED_CHICKEN("minecraft:cooked_chicken", 64, null),

    ROTTEN_FLESH("minecraft:rotten_flesh", 64, null),

    ENDER_PEARL("minecraft:ender_pearl", 64, null),

    BLAZE_ROD("minecraft:blaze_rod", 64, null),

    GHAST_TEAR("minecraft:ghast_tear", 64, null),

    GOLD_NUGGET("minecraft:gold_nugget", 64, null),

    NETHER_WART("minecraft:nether_wart", 64, Block.NETHER_WART),

    POTION("minecraft:potion", 64, null),

    GLASS_BOTTLE("minecraft:glass_bottle", 64, null),

    SPIDER_EYE("minecraft:spider_eye", 64, null),

    FERMENTED_SPIDER_EYE("minecraft:fermented_spider_eye", 64, null),

    BLAZE_POWDER("minecraft:blaze_powder", 64, null),

    MAGMA_CREAM("minecraft:magma_cream", 64, null),

    BREWING_STAND("minecraft:brewing_stand", 64, Block.BREWING_STAND),

    CAULDRON("minecraft:cauldron", 64, Block.CAULDRON),

    ENDER_EYE("minecraft:ender_eye", 64, null),

    SPECKLED_MELON("minecraft:speckled_melon", 64, null),

    SPAWN_EGG("minecraft:spawn_egg", 64, null),

    EXPERIENCE_BOTTLE("minecraft:experience_bottle", 64, null),

    FIRE_CHARGE("minecraft:fire_charge", 64, null),

    WRITABLE_BOOK("minecraft:writable_book", 64, null),

    WRITTEN_BOOK("minecraft:written_book", 16, null),

    EMERALD("minecraft:emerald", 64, null),

    ITEM_FRAME("minecraft:item_frame", 64, null),

    FLOWER_POT("minecraft:flower_pot", 64, Block.FLOWER_POT),

    CARROT("minecraft:carrot", 64, null),

    POTATO("minecraft:potato", 64, null),

    BAKED_POTATO("minecraft:baked_potato", 64, null),

    POISONOUS_POTATO("minecraft:poisonous_potato", 64, null),

    MAP("minecraft:map", 64, null),

    GOLDEN_CARROT("minecraft:golden_carrot", 64, null),

    SKULL("minecraft:skull", 64, Block.SKULL),

    CARROT_ON_A_STICK("minecraft:carrot_on_a_stick", 64, null),

    NETHER_STAR("minecraft:nether_star", 64, null),

    PUMPKIN_PIE("minecraft:pumpkin_pie", 64, null),

    FIREWORKS("minecraft:fireworks", 64, null),

    FIREWORK_CHARGE("minecraft:firework_charge", 64, null),

    ENCHANTED_BOOK("minecraft:enchanted_book", 1, null),

    COMPARATOR("minecraft:comparator", 64, Block.UNPOWERED_COMPARATOR),

    NETHERBRICK("minecraft:netherbrick", 64, null),

    QUARTZ("minecraft:quartz", 64, null),

    TNT_MINECART("minecraft:tnt_minecart", 64, null),

    HOPPER_MINECART("minecraft:hopper_minecart", 64, null),

    PRISMARINE_SHARD("minecraft:prismarine_shard", 64, null),

    PRISMARINE_CRYSTALS("minecraft:prismarine_crystals", 64, null),

    RABBIT("minecraft:rabbit", 64, null),

    COOKED_RABBIT("minecraft:cooked_rabbit", 64, null),

    RABBIT_STEW("minecraft:rabbit_stew", 64, null),

    RABBIT_FOOT("minecraft:rabbit_foot", 64, null),

    RABBIT_HIDE("minecraft:rabbit_hide", 64, null),

    ARMOR_STAND("minecraft:armor_stand", 16, null),

    IRON_HORSE_ARMOR("minecraft:iron_horse_armor", 1, null),

    GOLDEN_HORSE_ARMOR("minecraft:golden_horse_armor", 1, null),

    DIAMOND_HORSE_ARMOR("minecraft:diamond_horse_armor", 1, null),

    LEAD("minecraft:lead", 64, null),

    NAME_TAG("minecraft:name_tag", 64, null),

    COMMAND_BLOCK_MINECART("minecraft:command_block_minecart", 64, null),

    MUTTON("minecraft:mutton", 64, null),

    COOKED_MUTTON("minecraft:cooked_mutton", 64, null),

    BANNER("minecraft:banner", 64, null),

    SPRUCE_DOOR("minecraft:spruce_door", 64, Block.SPRUCE_DOOR),

    BIRCH_DOOR("minecraft:birch_door", 64, Block.BIRCH_DOOR),

    JUNGLE_DOOR("minecraft:jungle_door", 64, Block.JUNGLE_DOOR),

    ACACIA_DOOR("minecraft:acacia_door", 64, Block.ACACIA_DOOR),

    DARK_OAK_DOOR("minecraft:dark_oak_door", 64, Block.DARK_OAK_DOOR),

    RECORD_13("minecraft:record_13", 64, null),

    RECORD_CAT("minecraft:record_cat", 64, null),

    RECORD_BLOCKS("minecraft:record_blocks", 64, null),

    RECORD_CHIRP("minecraft:record_chirp", 64, null),

    RECORD_FAR("minecraft:record_far", 64, null),

    RECORD_MALL("minecraft:record_mall", 64, null),

    RECORD_MELLOHI("minecraft:record_mellohi", 64, null),

    RECORD_STAL("minecraft:record_stal", 64, null),

    RECORD_STRAD("minecraft:record_strad", 64, null),

    RECORD_WARD("minecraft:record_ward", 64, null),

    RECORD_11("minecraft:record_11", 64, null),

    RECORD_WAIT("minecraft:record_wait", 64, null);

    @NotNull
    private String namespaceID;

    private int maxDefaultStackSize;

    @Nullable
    private Block correspondingBlock;

    Material(@NotNull String namespaceID, int maxDefaultStackSize,
            @Nullable Block correspondingBlock) {
        this.namespaceID = namespaceID;
        this.maxDefaultStackSize = maxDefaultStackSize;
        this.correspondingBlock = correspondingBlock;
        Registries.materials.put(NamespaceID.from(namespaceID), this);
    }

    public short getId() {
        return (short)ordinal();
    }

    public String getName() {
        return namespaceID;
    }

    public int getMaxDefaultStackSize() {
        return maxDefaultStackSize;
    }

    public boolean isBlock() {
        return correspondingBlock != null && this != AIR;
    }

    public Block getBlock() {
        return correspondingBlock;
    }

    public static Material fromId(short id) {
        if(id >= 0 && id < values().length) {
            return values()[id];
        }
        return AIR;
    }

    public boolean isHelmet() {
        return toString().endsWith("HELMET");
    }

    public boolean isChestplate() {
        return toString().endsWith("CHESTPLATE");
    }

    public boolean isLeggings() {
        return toString().endsWith("LEGGINGS");
    }

    public boolean isBoots() {
        return toString().endsWith("BOOTS");
    }

    public boolean isArmor() {
        return isChestplate() || isHelmet() || isLeggings() || isBoots();
    }

    public boolean isFood() {
        switch(this) {
            case APPLE:
            case MUSHROOM_STEW:
            case BREAD:
            case PORKCHOP:
            case COOKED_PORKCHOP:
            case GOLDEN_APPLE:
            case FISH:
            case COOKED_FISH:
            case CAKE:
            case COOKIE:
            case MELON:
            case BEEF:
            case COOKED_BEEF:
            case CHICKEN:
            case COOKED_CHICKEN:
            case ROTTEN_FLESH:
            case SPIDER_EYE:
            case CARROT:
            case POTATO:
            case BAKED_POTATO:
            case POISONOUS_POTATO:
            case PUMPKIN_PIE:
            case RABBIT:
            case COOKED_RABBIT:
            case RABBIT_STEW:
            case MUTTON:
            case COOKED_MUTTON:
            return true;
        }
        return false;
    }

    public boolean hasState() {
        switch(this) {
            case BOW:
            return true;
        }
        return isFood();
    }
}
