package net.minestom.server.entity;

import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * //==============================
 * //  AUTOGENERATED BY EnumGenerator
 * //==============================
 */
@SuppressWarnings({"deprecation"})
public enum EntityType {
    BOAT("minecraft:Boat", 1),

    ITEM("minecraft:Item", 2),

    MINECART_RIDEABLE("minecraft:MinecartRideable", 12),

    MOB("minecraft:Mob", 48),

    MONSTER("minecraft:Monster", 49),

    CREEPER("minecraft:Creeper", 50),

    SKELETON("minecraft:Skeleton", 51),

    SPIDER("minecraft:Spider", 52),

    GIANT("minecraft:Giant", 53),

    ZOMBIE("minecraft:Zombie", 54),

    SLIME("minecraft:Slime", 55),

    GHAST("minecraft:Ghast", 56),

    PIG_ZOMBIE("minecraft:PigZombie", 57),

    ENDERMAN("minecraft:Enderman", 58),

    CAVE_SPIDER("minecraft:CaveSpider", 59),

    SILVERFISH("minecraft:Silverfish", 60),

    BLAZE("minecraft:Blaze", 61),

    LAVA_SLIME("minecraft:LavaSlime", 62),

    ENDER_DRAGON("minecraft:EnderDragon", 63),

    WITHER_BOSS("minecraft:WitherBoss", 64),

    BAT("minecraft:Bat", 65),

    WITCH("minecraft:Witch", 66),

    ENDERMITE("minecraft:Endermite", 67),

    GUARDIAN("minecraft:Guardian", 68),

    FALLING_SAND("minecraft:FallingSand", 74),

    ITEM_FRAME("minecraft:ItemFrame", 71),

    EYE_OF_ENDER_SIGNAL("minecraft:EyeOfEnderSignal", 72),

    THROWN_POTION("minecraft:ThrownPotion", 73),

    THROWN_EXP_BOTTLE("minecraft:ThrownExpBottle", 75),

    FIREWORKS_ROCKET_ENTITY("minecraft:FireworksRocketEntity", 76),

    LEASH_KNOT("minecraft:LeashKnot", 77),

    ARMOR_STAND("minecraft:ArmorStand", 78),

    PIG("minecraft:Pig", 90),

    SHEEP("minecraft:Sheep", 91),

    COW("minecraft:Cow", 92),

    CHICKEN("minecraft:Chicken", 93),

    SQUID("minecraft:Squid", 94),

    WOLF("minecraft:Wolf", 95),

    MUSHROOM_COW("minecraft:MushroomCow", 96),

    SNOW_MAN("minecraft:SnowMan", 97),

    OZELOT("minecraft:Ozelot", 98),

    VILLAGER_GOLEM("minecraft:VillagerGolem", 99),

    ENTITY_HORSE("minecraft:EntityHorse", 100),

    RABBIT("minecraft:Rabbit", 101),

    VILLAGER("minecraft:Villager", 120);

    private String namespaceID;

    private int id;

    EntityType(String namespaceID, int id) {
        this.namespaceID = namespaceID;
        this.id = id;
        Registries.entityTypes.put(NamespaceID.from(namespaceID), this);
    }

    public int getId() {
        return id;
    }

    public String getNamespaceID() {
        return namespaceID;
    }

    public static EntityType fromId(int id) {
        for (EntityType o : values()) {
            if (o.getId() == id) {
                return o;
            }
        }
        return null;
    }
}
