package net.minestom.server.entity;

import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * //==============================
 * //  AUTOGENERATED BY EnumGenerator
 * //==============================
 */
@SuppressWarnings({"deprecation"})
public enum EntityType {
    FISHING_FLOAT("minecraft:Fishing Float", 0, 90),

    ITEM("minecraft:Item", 1, 2),

    THROWN_EGG("minecraft:ThrownEgg", 7, 62),

    LEASH_KNOT("minecraft:LeashKnot", 8, 77),

    ARROW("minecraft:Arrow", 10, 60),

    SNOWBALL("minecraft:Snowball", 11, 61),

    FIREBALL("minecraft:Fireball", 12, 63),

    SMALL_FIREBALL("minecraft:SmallFireball", 13, 64),

    THROWN_ENDERPEARL("minecraft:ThrownEnderpearl", 14, 65),

    EYE_OF_ENDER_SIGNAL("minecraft:EyeOfEnderSignal", 15, 72),

    THROWN_POTION("minecraft:ThrownPotion", 16, 73),

    THROWN_EXP_BOTTLE("minecraft:ThrownExpBottle", 17, 75),

    ITEM_FRAME("minecraft:ItemFrame", 18, 71),

    WITHER_SKULL("minecraft:WitherSkull", 19, 66),

    PRIMED_TNT("minecraft:PrimedTnt", 20, 50),

    FALLING_SAND("minecraft:FallingSand", 21, 70),

    FIREWORKS_ROCKET_ENTITY("minecraft:FireworksRocketEntity", 22, 76),

    ARMOR_STAND("minecraft:ArmorStand", 30, 78),

    BOAT("minecraft:Boat", 41, 1),

    MINECART_RIDEABLE("minecraft:MinecartRideable", 42, 10),

    MOB("minecraft:Mob", 48, 48),

    MONSTER("minecraft:Monster", 49, 49),

    CREEPER("minecraft:Creeper", 50, 50),

    SKELETON("minecraft:Skeleton", 51, 51),

    SPIDER("minecraft:Spider", 52, 52),

    GIANT("minecraft:Giant", 53, 53),

    ZOMBIE("minecraft:Zombie", 54, 54),

    SLIME("minecraft:Slime", 55, 55),

    GHAST("minecraft:Ghast", 56, 56),

    PIG_ZOMBIE("minecraft:PigZombie", 57, 57),

    ENDERMAN("minecraft:Enderman", 58, 58),

    CAVE_SPIDER("minecraft:CaveSpider", 59, 59),

    SILVERFISH("minecraft:Silverfish", 60, 60),

    BLAZE("minecraft:Blaze", 61, 61),

    LAVA_SLIME("minecraft:LavaSlime", 62, 62),

    ENDER_DRAGON("minecraft:EnderDragon", 63, 63),

    WITHER_BOSS("minecraft:WitherBoss", 64, 64),

    BAT("minecraft:Bat", 65, 65),

    WITCH("minecraft:Witch", 66, 66),

    ENDERMITE("minecraft:Endermite", 67, 67),

    GUARDIAN("minecraft:Guardian", 68, 68),

    PIG("minecraft:Pig", 90, 90),

    SHEEP("minecraft:Sheep", 91, 91),

    COW("minecraft:Cow", 92, 92),

    CHICKEN("minecraft:Chicken", 93, 93),

    SQUID("minecraft:Squid", 94, 94),

    WOLF("minecraft:Wolf", 95, 95),

    MUSHROOM_COW("minecraft:MushroomCow", 96, 96),

    SNOW_MAN("minecraft:SnowMan", 97, 97),

    OZELOT("minecraft:Ozelot", 98, 98),

    VILLAGER_GOLEM("minecraft:VillagerGolem", 99, 99),

    ENTITY_HORSE("minecraft:EntityHorse", 100, 100),

    RABBIT("minecraft:Rabbit", 101, 101),

    VILLAGER("minecraft:Villager", 120, 120),

    ENDER_CRYSTAL("minecraft:EnderCrystal", 200, 51);

    private String namespaceID;

    private int id;

    private int protocolId;

    EntityType(String namespaceID, int id, int protocolId) {
        this.namespaceID = namespaceID;
        this.id = id;
        this.protocolId = protocolId;
        Registries.entityTypes.put(NamespaceID.from(namespaceID), this);
    }

    public int getId() {
        return id;
    }

    public int getProtocolId() {
        return protocolId;
    }

    public String getNamespaceID() {
        return namespaceID;
    }

    public static EntityType fromId(int id) {
        for (EntityType o : values()) {
            if (o.getId() == id) {
                return o;
            }
        }
        return null;
    }
}
