package net.minestom.server.sound;

import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * //==============================
 * //  AUTOGENERATED BY EnumGenerator
 * //==============================
 */
@SuppressWarnings({"deprecation"})
public enum Sound {
    AMBIENT_CAVE_CAVE("minecraft:ambient.cave.cave"),

    AMBIENT_WEATHER_RAIN("minecraft:ambient.weather.rain"),

    AMBIENT_WEATHER_THUNDER("minecraft:ambient.weather.thunder"),

    GAME_PLAYER_HURT_FALL_BIG("minecraft:game.player.hurt.fall.big"),

    GAME_PLAYER_HURT_FALL_SMALL("minecraft:game.player.hurt.fall.small"),

    GAME_NEUTRAL_HURT_FALL_BIG("minecraft:game.neutral.hurt.fall.big"),

    GAME_NEUTRAL_HURT_FALL_SMALL("minecraft:game.neutral.hurt.fall.small"),

    GAME_HOSTILE_HURT_FALL_BIG("minecraft:game.hostile.hurt.fall.big"),

    GAME_HOSTILE_HURT_FALL_SMALL("minecraft:game.hostile.hurt.fall.small"),

    GAME_PLAYER_HURT("minecraft:game.player.hurt"),

    GAME_NEUTRAL_HURT("minecraft:game.neutral.hurt"),

    GAME_HOSTILE_HURT("minecraft:game.hostile.hurt"),

    GAME_PLAYER_DIE("minecraft:game.player.die"),

    GAME_NEUTRAL_DIE("minecraft:game.neutral.die"),

    GAME_HOSTILE_DIE("minecraft:game.hostile.die"),

    DIG_CLOTH("minecraft:dig.cloth"),

    DIG_GRASS("minecraft:dig.grass"),

    DIG_GRAVEL("minecraft:dig.gravel"),

    DIG_SAND("minecraft:dig.sand"),

    DIG_SNOW("minecraft:dig.snow"),

    DIG_STONE("minecraft:dig.stone"),

    DIG_WOOD("minecraft:dig.wood"),

    FIRE_FIRE("minecraft:fire.fire"),

    FIRE_IGNITE("minecraft:fire.ignite"),

    ITEM_FIRECHARGE_USE("minecraft:item.fireCharge.use"),

    FIREWORKS_BLAST("minecraft:fireworks.blast"),

    FIREWORKS_BLAST_FAR("minecraft:fireworks.blast_far"),

    FIREWORKS_LARGEBLAST("minecraft:fireworks.largeBlast"),

    FIREWORKS_LARGEBLAST_FAR("minecraft:fireworks.largeBlast_far"),

    FIREWORKS_LAUNCH("minecraft:fireworks.launch"),

    FIREWORKS_TWINKLE("minecraft:fireworks.twinkle"),

    FIREWORKS_TWINKLE_FAR("minecraft:fireworks.twinkle_far"),

    LIQUID_LAVA("minecraft:liquid.lava"),

    LIQUID_LAVAPOP("minecraft:liquid.lavapop"),

    GAME_NEUTRAL_SWIM_SPLASH("minecraft:game.neutral.swim.splash"),

    GAME_PLAYER_SWIM_SPLASH("minecraft:game.player.swim.splash"),

    GAME_HOSTILE_SWIM_SPLASH("minecraft:game.hostile.swim.splash"),

    GAME_PLAYER_SWIM("minecraft:game.player.swim"),

    GAME_NEUTRAL_SWIM("minecraft:game.neutral.swim"),

    GAME_HOSTILE_SWIM("minecraft:game.hostile.swim"),

    LIQUID_WATER("minecraft:liquid.water"),

    MINECART_BASE("minecraft:minecart.base"),

    MINECART_INSIDE("minecraft:minecart.inside"),

    MOB_BAT_DEATH("minecraft:mob.bat.death"),

    MOB_BAT_HURT("minecraft:mob.bat.hurt"),

    MOB_BAT_IDLE("minecraft:mob.bat.idle"),

    MOB_BAT_LOOP("minecraft:mob.bat.loop"),

    MOB_BAT_TAKEOFF("minecraft:mob.bat.takeoff"),

    MOB_BLAZE_BREATHE("minecraft:mob.blaze.breathe"),

    MOB_BLAZE_DEATH("minecraft:mob.blaze.death"),

    MOB_BLAZE_HIT("minecraft:mob.blaze.hit"),

    MOB_GUARDIAN_HIT("minecraft:mob.guardian.hit"),

    MOB_GUARDIAN_IDLE("minecraft:mob.guardian.idle"),

    MOB_GUARDIAN_DEATH("minecraft:mob.guardian.death"),

    MOB_GUARDIAN_ELDER_HIT("minecraft:mob.guardian.elder.hit"),

    MOB_GUARDIAN_ELDER_IDLE("minecraft:mob.guardian.elder.idle"),

    MOB_GUARDIAN_ELDER_DEATH("minecraft:mob.guardian.elder.death"),

    MOB_GUARDIAN_LAND_HIT("minecraft:mob.guardian.land.hit"),

    MOB_GUARDIAN_LAND_IDLE("minecraft:mob.guardian.land.idle"),

    MOB_GUARDIAN_LAND_DEATH("minecraft:mob.guardian.land.death"),

    MOB_GUARDIAN_CURSE("minecraft:mob.guardian.curse"),

    MOB_GUARDIAN_ATTACK("minecraft:mob.guardian.attack"),

    MOB_GUARDIAN_FLOP("minecraft:mob.guardian.flop"),

    MOB_CAT_HISS("minecraft:mob.cat.hiss"),

    MOB_CAT_HITT("minecraft:mob.cat.hitt"),

    MOB_CAT_MEOW("minecraft:mob.cat.meow"),

    MOB_CAT_PURR("minecraft:mob.cat.purr"),

    MOB_CAT_PURREOW("minecraft:mob.cat.purreow"),

    MOB_CHICKEN_HURT("minecraft:mob.chicken.hurt"),

    MOB_CHICKEN_PLOP("minecraft:mob.chicken.plop"),

    MOB_CHICKEN_SAY("minecraft:mob.chicken.say"),

    MOB_CHICKEN_STEP("minecraft:mob.chicken.step"),

    MOB_COW_HURT("minecraft:mob.cow.hurt"),

    MOB_COW_SAY("minecraft:mob.cow.say"),

    MOB_COW_STEP("minecraft:mob.cow.step"),

    MOB_CREEPER_DEATH("minecraft:mob.creeper.death"),

    MOB_CREEPER_SAY("minecraft:mob.creeper.say"),

    MOB_ENDERDRAGON_END("minecraft:mob.enderdragon.end"),

    MOB_ENDERDRAGON_GROWL("minecraft:mob.enderdragon.growl"),

    MOB_ENDERDRAGON_HIT("minecraft:mob.enderdragon.hit"),

    MOB_ENDERDRAGON_WINGS("minecraft:mob.enderdragon.wings"),

    MOB_ENDERMEN_DEATH("minecraft:mob.endermen.death"),

    MOB_ENDERMEN_HIT("minecraft:mob.endermen.hit"),

    MOB_ENDERMEN_IDLE("minecraft:mob.endermen.idle"),

    MOB_ENDERMEN_PORTAL("minecraft:mob.endermen.portal"),

    MOB_ENDERMEN_SCREAM("minecraft:mob.endermen.scream"),

    MOB_ENDERMEN_STARE("minecraft:mob.endermen.stare"),

    MOB_GHAST_AFFECTIONATE_SCREAM("minecraft:mob.ghast.affectionate_scream"),

    MOB_GHAST_CHARGE("minecraft:mob.ghast.charge"),

    MOB_GHAST_DEATH("minecraft:mob.ghast.death"),

    MOB_GHAST_FIREBALL("minecraft:mob.ghast.fireball"),

    MOB_GHAST_MOAN("minecraft:mob.ghast.moan"),

    MOB_GHAST_SCREAM("minecraft:mob.ghast.scream"),

    MOB_HORSE_ANGRY("minecraft:mob.horse.angry"),

    MOB_HORSE_ARMOR("minecraft:mob.horse.armor"),

    MOB_HORSE_BREATHE("minecraft:mob.horse.breathe"),

    MOB_HORSE_DEATH("minecraft:mob.horse.death"),

    MOB_HORSE_DONKEY_ANGRY("minecraft:mob.horse.donkey.angry"),

    MOB_HORSE_DONKEY_DEATH("minecraft:mob.horse.donkey.death"),

    MOB_HORSE_DONKEY_HIT("minecraft:mob.horse.donkey.hit"),

    MOB_HORSE_DONKEY_IDLE("minecraft:mob.horse.donkey.idle"),

    MOB_HORSE_GALLOP("minecraft:mob.horse.gallop"),

    MOB_HORSE_HIT("minecraft:mob.horse.hit"),

    MOB_HORSE_IDLE("minecraft:mob.horse.idle"),

    MOB_HORSE_JUMP("minecraft:mob.horse.jump"),

    MOB_HORSE_LAND("minecraft:mob.horse.land"),

    MOB_HORSE_LEATHER("minecraft:mob.horse.leather"),

    MOB_HORSE_SKELETON_DEATH("minecraft:mob.horse.skeleton.death"),

    MOB_HORSE_SKELETON_HIT("minecraft:mob.horse.skeleton.hit"),

    MOB_HORSE_SKELETON_IDLE("minecraft:mob.horse.skeleton.idle"),

    MOB_HORSE_SOFT("minecraft:mob.horse.soft"),

    MOB_HORSE_WOOD("minecraft:mob.horse.wood"),

    MOB_HORSE_ZOMBIE_DEATH("minecraft:mob.horse.zombie.death"),

    MOB_HORSE_ZOMBIE_HIT("minecraft:mob.horse.zombie.hit"),

    MOB_HORSE_ZOMBIE_IDLE("minecraft:mob.horse.zombie.idle"),

    MOB_IRONGOLEM_DEATH("minecraft:mob.irongolem.death"),

    MOB_IRONGOLEM_HIT("minecraft:mob.irongolem.hit"),

    MOB_IRONGOLEM_THROW("minecraft:mob.irongolem.throw"),

    MOB_IRONGOLEM_WALK("minecraft:mob.irongolem.walk"),

    MOB_MAGMACUBE_BIG("minecraft:mob.magmacube.big"),

    MOB_MAGMACUBE_JUMP("minecraft:mob.magmacube.jump"),

    MOB_MAGMACUBE_SMALL("minecraft:mob.magmacube.small"),

    MOB_PIG_DEATH("minecraft:mob.pig.death"),

    MOB_PIG_SAY("minecraft:mob.pig.say"),

    MOB_PIG_STEP("minecraft:mob.pig.step"),

    MOB_RABBIT_HURT("minecraft:mob.rabbit.hurt"),

    MOB_RABBIT_IDLE("minecraft:mob.rabbit.idle"),

    MOB_RABBIT_HOP("minecraft:mob.rabbit.hop"),

    MOB_RABBIT_DEATH("minecraft:mob.rabbit.death"),

    MOB_SHEEP_SAY("minecraft:mob.sheep.say"),

    MOB_SHEEP_SHEAR("minecraft:mob.sheep.shear"),

    MOB_SHEEP_STEP("minecraft:mob.sheep.step"),

    MOB_SILVERFISH_HIT("minecraft:mob.silverfish.hit"),

    MOB_SILVERFISH_KILL("minecraft:mob.silverfish.kill"),

    MOB_SILVERFISH_SAY("minecraft:mob.silverfish.say"),

    MOB_SILVERFISH_STEP("minecraft:mob.silverfish.step"),

    MOB_SKELETON_DEATH("minecraft:mob.skeleton.death"),

    MOB_SKELETON_HURT("minecraft:mob.skeleton.hurt"),

    MOB_SKELETON_SAY("minecraft:mob.skeleton.say"),

    MOB_SKELETON_STEP("minecraft:mob.skeleton.step"),

    MOB_SLIME_ATTACK("minecraft:mob.slime.attack"),

    MOB_SLIME_BIG("minecraft:mob.slime.big"),

    MOB_SLIME_SMALL("minecraft:mob.slime.small"),

    MOB_SPIDER_DEATH("minecraft:mob.spider.death"),

    MOB_SPIDER_SAY("minecraft:mob.spider.say"),

    MOB_SPIDER_STEP("minecraft:mob.spider.step"),

    MOB_VILLAGER_DEATH("minecraft:mob.villager.death"),

    MOB_VILLAGER_HAGGLE("minecraft:mob.villager.haggle"),

    MOB_VILLAGER_HIT("minecraft:mob.villager.hit"),

    MOB_VILLAGER_IDLE("minecraft:mob.villager.idle"),

    MOB_VILLAGER_NO("minecraft:mob.villager.no"),

    MOB_VILLAGER_YES("minecraft:mob.villager.yes"),

    MOB_WITHER_DEATH("minecraft:mob.wither.death"),

    MOB_WITHER_HURT("minecraft:mob.wither.hurt"),

    MOB_WITHER_IDLE("minecraft:mob.wither.idle"),

    MOB_WITHER_SHOOT("minecraft:mob.wither.shoot"),

    MOB_WITHER_SPAWN("minecraft:mob.wither.spawn"),

    MOB_WOLF_BARK("minecraft:mob.wolf.bark"),

    MOB_WOLF_DEATH("minecraft:mob.wolf.death"),

    MOB_WOLF_GROWL("minecraft:mob.wolf.growl"),

    MOB_WOLF_HOWL("minecraft:mob.wolf.howl"),

    MOB_WOLF_HURT("minecraft:mob.wolf.hurt"),

    MOB_WOLF_PANTING("minecraft:mob.wolf.panting"),

    MOB_WOLF_SHAKE("minecraft:mob.wolf.shake"),

    MOB_WOLF_STEP("minecraft:mob.wolf.step"),

    MOB_WOLF_WHINE("minecraft:mob.wolf.whine"),

    MOB_ZOMBIE_DEATH("minecraft:mob.zombie.death"),

    MOB_ZOMBIE_HURT("minecraft:mob.zombie.hurt"),

    MOB_ZOMBIE_INFECT("minecraft:mob.zombie.infect"),

    MOB_ZOMBIE_METAL("minecraft:mob.zombie.metal"),

    MOB_ZOMBIE_REMEDY("minecraft:mob.zombie.remedy"),

    MOB_ZOMBIE_SAY("minecraft:mob.zombie.say"),

    MOB_ZOMBIE_STEP("minecraft:mob.zombie.step"),

    MOB_ZOMBIE_UNFECT("minecraft:mob.zombie.unfect"),

    MOB_ZOMBIE_WOOD("minecraft:mob.zombie.wood"),

    MOB_ZOMBIE_WOODBREAK("minecraft:mob.zombie.woodbreak"),

    MOB_ZOMBIEPIG_ZPIG("minecraft:mob.zombiepig.zpig"),

    MOB_ZOMBIEPIG_ZPIGANGRY("minecraft:mob.zombiepig.zpigangry"),

    MOB_ZOMBIEPIG_ZPIGDEATH("minecraft:mob.zombiepig.zpigdeath"),

    MOB_ZOMBIEPIG_ZPIGHURT("minecraft:mob.zombiepig.zpighurt"),

    NOTE_BASS("minecraft:note.bass"),

    NOTE_BASSATTACK("minecraft:note.bassattack"),

    NOTE_BD("minecraft:note.bd"),

    NOTE_HARP("minecraft:note.harp"),

    NOTE_HAT("minecraft:note.hat"),

    NOTE_PLING("minecraft:note.pling"),

    NOTE_SNARE("minecraft:note.snare"),

    PORTAL_PORTAL("minecraft:portal.portal"),

    PORTAL_TRAVEL("minecraft:portal.travel"),

    PORTAL_TRIGGER("minecraft:portal.trigger"),

    RANDOM_ANVIL_BREAK("minecraft:random.anvil_break"),

    RANDOM_ANVIL_LAND("minecraft:random.anvil_land"),

    RANDOM_ANVIL_USE("minecraft:random.anvil_use"),

    RANDOM_BOW("minecraft:random.bow"),

    RANDOM_BOWHIT("minecraft:random.bowhit"),

    RANDOM_BREAK("minecraft:random.break"),

    RANDOM_BURP("minecraft:random.burp"),

    RANDOM_CHESTCLOSED("minecraft:random.chestclosed"),

    RANDOM_CHESTOPEN("minecraft:random.chestopen"),

    GUI_BUTTON_PRESS("minecraft:gui.button.press"),

    RANDOM_CLICK("minecraft:random.click"),

    RANDOM_DOOR_CLOSE("minecraft:random.door_close"),

    RANDOM_DOOR_OPEN("minecraft:random.door_open"),

    RANDOM_DRINK("minecraft:random.drink"),

    RANDOM_EAT("minecraft:random.eat"),

    RANDOM_EXPLODE("minecraft:random.explode"),

    RANDOM_FIZZ("minecraft:random.fizz"),

    GAME_TNT_PRIMED("minecraft:game.tnt.primed"),

    CREEPER_PRIMED("minecraft:creeper.primed"),

    DIG_GLASS("minecraft:dig.glass"),

    GAME_POTION_SMASH("minecraft:game.potion.smash"),

    RANDOM_LEVELUP("minecraft:random.levelup"),

    RANDOM_ORB("minecraft:random.orb"),

    RANDOM_POP("minecraft:random.pop"),

    RANDOM_SPLASH("minecraft:random.splash"),

    RANDOM_SUCCESSFUL_HIT("minecraft:random.successful_hit"),

    RANDOM_WOOD_CLICK("minecraft:random.wood_click"),

    RECORDS_11("minecraft:records.11"),

    RECORDS_13("minecraft:records.13"),

    RECORDS_BLOCKS("minecraft:records.blocks"),

    RECORDS_CAT("minecraft:records.cat"),

    RECORDS_CHIRP("minecraft:records.chirp"),

    RECORDS_FAR("minecraft:records.far"),

    RECORDS_MALL("minecraft:records.mall"),

    RECORDS_MELLOHI("minecraft:records.mellohi"),

    RECORDS_STAL("minecraft:records.stal"),

    RECORDS_STRAD("minecraft:records.strad"),

    RECORDS_WAIT("minecraft:records.wait"),

    RECORDS_WARD("minecraft:records.ward"),

    STEP_CLOTH("minecraft:step.cloth"),

    STEP_GRASS("minecraft:step.grass"),

    STEP_GRAVEL("minecraft:step.gravel"),

    STEP_LADDER("minecraft:step.ladder"),

    STEP_SAND("minecraft:step.sand"),

    STEP_SNOW("minecraft:step.snow"),

    STEP_STONE("minecraft:step.stone"),

    STEP_WOOD("minecraft:step.wood"),

    TILE_PISTON_IN("minecraft:tile.piston.in"),

    TILE_PISTON_OUT("minecraft:tile.piston.out"),

    MUSIC_MENU("minecraft:music.menu"),

    MUSIC_GAME("minecraft:music.game"),

    MUSIC_GAME_CREATIVE("minecraft:music.game.creative"),

    MUSIC_GAME_END("minecraft:music.game.end"),

    MUSIC_GAME_END_DRAGON("minecraft:music.game.end.dragon"),

    MUSIC_GAME_END_CREDITS("minecraft:music.game.end.credits"),

    MUSIC_GAME_NETHER("minecraft:music.game.nether");

    private String namespaceID;

    Sound(String namespaceID) {
        this.namespaceID = namespaceID;
        Registries.sounds.put(NamespaceID.from(namespaceID), this);
    }

    public String getNamespaceID() {
        return namespaceID;
    }
}
